# Generated by Django 2.1.7 on 2022-11-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('International', 'International'), ('Domestic', 'Domestic')], max_length=100)),
            ],
            options={
                'verbose_name': 'Conferences',
                'verbose_name_plural': 'Conferencess',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('International', 'International'), ('Domestic', 'Domestic')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Active', 'Active'), ('Finish', 'Finish')], max_length=100)),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projectss',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Yproject', to='journal.Year'),
        ),
        migrations.AddField(
            model_name='papers',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ypaper', to='journal.Year'),
        ),
        migrations.AddField(
            model_name='conferences',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Yconfer', to='journal.Year'),
        ),
    ]
