# Generated by Django 2.1.7 on 2022-11-09 15:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='research')),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=200)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
