# Generated by Django 2.1.7 on 2022-11-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferences',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papers',
            name='ordering',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='ordering',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
