# Generated by Django 2.1.7 on 2022-11-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20221109_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
