# Generated by Django 2.1.7 on 2022-11-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20221110_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
