# Generated by Django 2.1.7 on 2022-11-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20221110_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patents',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
