# Generated by Django 2.1.7 on 2022-11-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20221110_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='one_word_title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
