# Generated by Django 2.1.7 on 2022-11-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filejokbo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='fileshare',
            name='post',
        ),
        migrations.DeleteModel(
            name='FileJokbo',
        ),
        migrations.DeleteModel(
            name='FileShare',
        ),
    ]
