# Generated by Django 2.1.7 on 2022-11-04 12:25

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('writerName', models.CharField(blank=True, max_length=20)),
                ('writerStuNo', models.CharField(blank=True, max_length=3)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, default='', max_length=50)),
                ('tag', models.CharField(choices=[('행사', '행사'), ('대회', '대회'), ('프젝', '프젝'), ('기타', '기타')], default='공지', max_length=10)),
                ('depth', models.IntegerField(default=0)),
                ('imageLink', models.CharField(blank=True, default='/static/img/sample/document-icon.png', max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.PostActivity')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Comments', max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('writerName', models.CharField(blank=True, max_length=20)),
                ('writerStuNo', models.CharField(blank=True, max_length=3)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, default='', max_length=50)),
                ('depth', models.IntegerField(default=0)),
                ('imageLink', models.CharField(blank=True, default='/static/img/sample/document-icon.png', max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.PostFree')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostJokbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Comments', max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('writerName', models.CharField(blank=True, max_length=20)),
                ('writerStuNo', models.CharField(blank=True, max_length=3)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, default='', max_length=50)),
                ('depth', models.IntegerField(default=0)),
                ('tag', models.CharField(choices=[('수학', '수학'), ('프로그래밍', '프로그래밍'), ('이론', '이론'), ('기타', '기타')], default='기타', max_length=10)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.PostJokbo')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('writerName', models.CharField(blank=True, max_length=20)),
                ('writerStuNo', models.CharField(blank=True, max_length=3)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, default='', max_length=50)),
                ('tag', models.CharField(default='공지', max_length=10)),
                ('depth', models.IntegerField(default=0)),
                ('imageLink', models.CharField(blank=True, default='/static/img/sample/document-icon.png', max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.PostNotice')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Comments', max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('writerName', models.CharField(blank=True, max_length=20)),
                ('writerStuNo', models.CharField(blank=True, max_length=3)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, default='', max_length=50)),
                ('tag', models.CharField(choices=[('프론트', '프론트'), ('서버', '서버'), ('데이터', '데이터'), ('클라우드', '클라우드'), ('기타', '기타')], default='기타', max_length=10)),
                ('depth', models.IntegerField(default=0)),
                ('imageLink', models.CharField(blank=True, default='/static/img/sample/document-icon.png', max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.PostShare')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Comments', max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('writerName', models.CharField(blank=True, max_length=20)),
                ('writerStuNo', models.CharField(blank=True, max_length=3)),
                ('hit', models.IntegerField(default=0)),
                ('writedAt', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, default='', max_length=50)),
                ('startDate', models.DateField(verbose_name='date study started')),
                ('endDate', models.DateField(verbose_name='date study ended')),
                ('time', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[('교과', '교과'), ('데이터', '데이터'), ('프론트', '프론트'), ('백', '백'), ('기타', '기타')], default='공지', max_length=10)),
                ('depth', models.IntegerField(default=0)),
                ('imageLink', models.CharField(blank=True, default='/static/img/sample/document-icon.png', max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.PostStudy')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostStudyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('studyIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostStudy')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
