# Generated by Django 2.1.7 on 2022-11-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfree',
            name='tag',
            field=models.CharField(default='News', max_length=50),
        ),
    ]
