# Generated by Django 2.1.7 on 2022-11-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postfree_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poststudy',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='poststudy',
            name='startDate',
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='tag',
            field=models.CharField(choices=[('수상', '수상'), ('발표', '발표'), ('학회', '학회'), ('기타', '기타')], default='기타', max_length=10),
        ),
    ]
