# Generated by Django 2.1.7 on 2022-11-10 01:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0002_auto_20221110_0138'),
        ('post', '0004_remove_poststudy_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostFree',
            new_name='PostNews',
        ),
        migrations.RenameModel(
            old_name='PostStudy',
            new_name='PostOutstanding',
        ),
        migrations.RenameModel(
            old_name='PostStudyMember',
            new_name='PostOutstandingMember',
        ),
        migrations.RemoveField(
            model_name='postjokbo',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='postjokbo',
            name='userIdx',
        ),
        migrations.RemoveField(
            model_name='postshare',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='postshare',
            name='userIdx',
        ),
        migrations.DeleteModel(
            name='PostJokbo',
        ),
        migrations.DeleteModel(
            name='PostShare',
        ),
    ]
