# Generated by Django 2.1.7 on 2022-11-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20221109_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Inter', 'Inter'), ('Res', 'Res'), ('Edu', 'Edu')], max_length=50, verbose_name='')),
                ('des', models.CharField(max_length=500, verbose_name='des')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_time', to='member.Professor')),
            ],
        ),
        migrations.RemoveField(
            model_name='name',
            name='name',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
