# Generated by Django 2.1.7 on 2022-11-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20221109_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='category',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Edu', 'Edu'), ('Res', 'Res')], max_length=50, verbose_name=''),
        ),
    ]
