# Generated by Django 2.1.7 on 2022-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20221109_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='category',
            field=models.CharField(choices=[('Res', 'Res'), ('Edu', 'Edu'), ('Inter', 'Inter')], max_length=50, verbose_name=''),
        ),
    ]
