# Generated by Django 2.1.7 on 2022-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20221109_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='category',
            field=models.CharField(choices=[('Edu', 'Edu'), ('Res', 'Res'), ('Inter', 'Inter')], max_length=50, verbose_name=''),
        ),
    ]
