# Generated by Django 2.1.7 on 2022-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20221109_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('PH.D', 'PH.D'), ('Post Graduate', 'Post Graduate'), ('Undergraduate', 'Undergraduate')], max_length=13),
        ),
    ]
