# Generated by Django 2.1.7 on 2022-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_remove_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='category',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Edu', 'Edu'), ('Res', 'Res')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='des',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
