# Generated by Django 2.1.7 on 2022-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20221109_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='since',
            field=models.DateField(),
        ),
    ]
