# Generated by Django 2.1.7 on 2022-11-06 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stuNo', models.CharField(max_length=3)),
                ('phoneNum', models.CharField(default='010-0000-0000', max_length=20)),
                ('github', models.URLField(blank=True)),
                ('group', models.IntegerField(default=0)),
            ],
        ),
    ]
