# Generated by Django 2.1.7 on 2022-11-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('skin', models.CharField(max_length=10)),
            ],
        ),
    ]
